title: Łukasz Biel
author:
  name: luke-biel
  email: lukasz.p.biel@gmail.com
description: >
  Rust and C#. Backend dev from Wrocław. Sometimes I make games.
show_excerpts: true

google_analytics: UA-159922407-1

disqus:
  shortname: luke-biel-github-io

minima:
  date_format: "%b %-d, %Y"

  social_links:
    twitter: dot_luke_biel
    github:  luke-biel
    linkedin: łukasz-biel-833759137

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

feed:
  categories:
    - technology
